// Generated by CoffeeScript 1.7.1
(function() {
  var Handler, exports,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Handler = (function() {
    Handler.prototype.protocol = void 0;

    Handler.prototype.routers = void 0;

    Handler.prototype.dispatch = function(ctx) {
      var router;
      router = this.bi.router;
      if (router.resolve(ctx)) {
        return router.dispatch(ctx);
      }
      return ctx.send('Could not find route', 404);
    };

    Handler.prototype.normalize = function(request, response) {
      throw 'Missing normalize method.';
    };

    function Handler(bi) {
      this.bi = bi;
      this.normalize = __bind(this.normalize, this);
      this.dispatch = __bind(this.dispatch, this);
      throw 'Missing constructor.';
    }

    return Handler;

  })();

  exports = module.exports = Handler;

}).call(this);

//# sourceMappingURL=handler.map
